import Head from 'next/head';
import RegisterForm from '../src/components/RegisterForm/RegisterForm';
import LoginForm from '../src/components/LoginForm/LoginForm';

import Test from '../src/components/Test/Test';

export default function Home() {
  return (
    <>
      <Head>
        <title>Search project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Test />
      {/*<RegisterForm />*/}
      <LoginForm />
    </>
  );
}
